services:
  nginx-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8180:80"
      - "8443:443"
    networks:
      proxy-net:
        ipv4_address: 10.10.10.2
      app1-net:
      app2-net:
      app3-net:
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: app1
    networks:
      app1-net:
        ipv4_address: 10.10.10.21
      db1-net:
        ipv4_address: 10.10.10.69
    environment:
      - DB_HOST=10.10.10.66
      - DB_USER=root
      - DB_PASSWORD=senha
      - DB_NAME=app1_db
    depends_on:
      - db1
    # ports:
    #   - "8081:80"
    volumes:
      - ./app1:/var/www/html

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: app2
    networks:
      app2-net:
        ipv4_address: 10.10.10.36
      db2-net:
        ipv4_address: 10.10.10.86
    environment:
      - DB_HOST=10.10.10.82
      - DB_USER=root
      - DB_PASSWORD=senha
      - DB_NAME=app2_db
    depends_on:
      - db2
    # ports:
    #   - "8082:80"
    volumes:
      - ./app2:/var/www/html


  app3:
    build:
      context: ./app3
      dockerfile: Dockerfile
    container_name: app3
    networks:
      app3-net:
        ipv4_address: 10.10.10.54
      db3-net:
        ipv4_address: 10.10.10.101
    environment:
      - DB_HOST=10.10.10.98
      - DB_USER=root
      - DB_PASSWORD=senha
      - DB_NAME=app3_db
    depends_on:
      - db3
    # ports:
    #   - "8083:80"
    volumes:
      - ./app3:/var/www/html

  db1:
    image: mysql:5.7
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    networks:
      db1-net:
        ipv4_address: 10.10.10.66

  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    networks:
      db2-net:
        ipv4_address: 10.10.10.82

  db3:
    image: mysql:5.7
    container_name: db3
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    networks:
      db3-net:
        ipv4_address: 10.10.10.98

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=db1,db2,db3
      - PMA_USER=root
      - PMA_PASSWORD=senha
    # ports:
    #   - "8086:80"
    networks:
      - proxy-net 
      - db1-net
      - db2-net
      - db3-net

  jadilsonpaiva-db1:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva-db1
    environment:
      - TERM=xterm
    tty: true
    stdin_open: true
    networks:
      db1-net:
        ipv4_address: 10.10.10.68
      db1-backup-net:
        ipv4_address: 10.10.10.114

  jadilsonpaiva-db2:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva-db2
    environment:
      - TERM=xterm
    tty: true
    stdin_open: true
    networks:
      db2-net:
        ipv4_address: 10.10.10.84
      db2-backup-net:
        ipv4_address: 10.10.10.130

  jadilsonpaiva-db3:
    image: jadilsonpaiva/full
    container_name: jadilsonpaiva-db3
    environment:
      - TERM=xterm
    tty: true
    stdin_open: true
    networks:
      db3-net:
        ipv4_address: 10.10.10.100
      db3-backup-net:
        ipv4_address: 10.10.10.146

networks:
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28

  app1-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.16/28

  app2-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.32/28

  app3-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.48/28

  db1-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.64/28

  db2-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.80/28

  db3-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.96/28

  db1-backup-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.112/28

  db2-backup-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.128/28

  db3-backup-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.144/28